# Generated by Django 2.2.18 on 2021-02-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_subject', models.CharField(max_length=100)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded')),
                ('exam_date', models.DateTimeField(blank=True, verbose_name='Examination Date')),
                ('exam_span', models.IntegerField(default=15, verbose_name='Examination Span Time')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Uploader')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='exams/')),
                ('answer_format', models.CharField(choices=[('abc', 'ABC'), ('true_false', 'True or False'), ('short', 'Short Sentence'), ('essay', 'Essay/ Sentence'), ('solution', 'Mathematical Solution')], default='abc', max_length=20)),
                ('answer', models.CharField(max_length=299)),
                ('exam_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamDetail', verbose_name='Exam detail')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=299)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamQuestion', verbose_name='Exam detail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Student')),
            ],
        ),
    ]
