# Generated by Django 2.2.18 on 2021-02-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
    ]
