# Generated by Django 2.2.18 on 2021-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examanswer_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='answer_choices',
            field=models.TextField(blank=True),
        ),
    ]
