# Generated by Django 2.2.18 on 2021-02-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examquestion_answer_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamQuestion', verbose_name='Exam detail'),
        ),
    ]
