# Generated by Django 2.2.18 on 2021-02-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210205_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=999, verbose_name='Password'),
        ),
    ]
